# Generated by Django 5.1.1 on 2024-09-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post',)},
        ),
        migrations.RemoveField(
            model_name='like',
            name='ip_address',
        ),
    ]
