# Generated by Django 5.1.1 on 2024-09-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip_address',
        ),
    ]
